#!/bin/sh

exec 1>&2

exec < /dev/tty

#regex to search for secrets
regex="\+.*(s|S)ecret.*=.*(\"|').+(\"|')"

if test $(git diff --cached | egrep $regex | wc -l) != 0
then
	exec git diff --cached | egrep $regex

	cat <<\EOF

	git diff --cached | egrep "\+.*(s|S)ecret.*=.*(\"|').+(\"|')"

	Warning: Possible secret detected in your code

EOF

	read -p "Do you want to continue? (y/n)" yn

	echo $yn | grep ^[Yy]$

	if [ $? -eq 0 ]
	then
		exit 0;
	fi

	exit 1
fi
